import qrcode from 'qrcode-generator';
import './style.css';

const types = {
  link: { label:'Link / Text', icon:'↗', fields:[['content','URL or text','textarea','https://example.com']] },
  whatsapp: { label:'WhatsApp', icon:'◉', fields:[['phone','Phone number','text','919876543210'],['message','Prefilled message','textarea','Hi! I would like to know more.']] },
  upi: { label:'UPI Payment', icon:'₹', fields:[['upi','UPI ID','text','name@upi'],['payee','Payee name','text','Your Business'],['amount','Amount (optional)','number','500'],['note','Payment note','text','Order payment']] },
  wifi: { label:'Wi-Fi', icon:'⌁', fields:[['ssid','Network name','text','My Wi-Fi'],['password','Password','text',''],['security','Security','select','WPA|WEP|None'],['hidden','Hidden network','select','No|Yes']] },
  vcard: { label:'Visiting Card', icon:'▣', fields:[['name','Full name','text','Aarav Sharma'],['company','Company','text',''],['phone','Phone','text',''],['email','Email','email',''],['address','Address','textarea',''],['website','Website / social link','url','']] },
  email: { label:'Email', icon:'@', fields:[['email','Email address','email','hello@example.com'],['subject','Subject','text','Hello'],['body','Message','textarea','']] },
  phone: { label:'Phone', icon:'☎', fields:[['phone','Phone number','tel','+91 98765 43210']] },
  menu: { label:'Menu', icon:'☷', fields:[['content','Menu PDF or webpage link','url','https://restaurant.example/menu.pdf'],['menuName','Menu name','text','Our menu']] }
};
let state={type:'link', dark:'#17211c', light:'#ffffff', size:1024, ecc:'H', logo:null};

document.querySelector('#app').innerHTML=`
  <header class="topbar"><div class="brand"><span class="brand-mark">▦</span> QR Bharat</div><div class="privacy">● <span>100% private · works in your browser</span></div></header>
  <main><section class="hero"><div><span class="eyebrow">✦ Scan. Connect. Done.</span><h1>One tiny square.<br>Endless possibilities.</h1><p>Create beautiful, reliable QR codes for payments, Wi-Fi, WhatsApp, menus and more. Nothing is uploaded. Nothing is stored.</p></div><div class="hero-art"><div class="mini-qr"><div class="mini-grid"></div></div></div></section>
  <section class="workspace"><div><div class="panel editor"><div class="tabs" id="tabs"></div><div class="section-title"><h2 id="formTitle"></h2><span class="badge">NO SIGN-UP</span></div><div class="form-grid" id="fields"></div>
  <div class="customize"><div class="section-title"><h2>Make it yours</h2></div><div class="custom-row"><div class="field"><label>QR color</label><input class="color-input" id="dark" type="color" value="#17211c"></div><div class="field"><label>Background</label><input class="color-input" id="light" type="color" value="#ffffff"></div><div class="field"><label>Add logo</label><div class="logo-drop">＋ Choose image<input id="logo" type="file" accept="image/*"></div></div><div class="field"><label>Image size</label><select id="size"><option value="512">512 × 512</option><option value="1024" selected>1024 × 1024</option><option value="2048">2048 × 2048</option></select></div><div class="field"><label>Error correction</label><select id="ecc"><option value="L">Low · 7%</option><option value="M">Medium · 15%</option><option value="Q">Quartile · 25%</option><option value="H" selected>High · 30%</option></select></div></div></div></div>
  <div class="shop-banner"><div><h3>Need a complete shop QR kit?</h3><p>Put payment, ordering, directions and contact on one printable A4 poster.</p></div><button id="shopKit">Create shop poster →</button></div></div>
  <aside class="panel preview"><div class="preview-head"><h2>Your QR code</h2><span class="live">Live preview</span></div><div class="qr-stage"><canvas id="qrCanvas"></canvas></div><p class="hint">Try scanning with your phone camera</p><div class="actions"><button class="btn primary" id="png">↓ PNG</button><button class="btn secondary" id="svg">↓ SVG</button></div><div class="local-note">🔒 Your information never leaves this device. QR codes are generated locally in your browser.</div></aside></section></main>
  <div class="poster-modal" id="posterModal"><div class="modal-card"><div class="modal-top"><h2>Indian shop QR kit</h2><button class="icon-btn" id="closeModal">×</button></div><div class="poster-form"><div class="poster-fields"><div class="field"><label>Shop name</label><input id="shopName" value="Your Shop Name"></div><div class="field"><label>UPI ID</label><input id="posterUpi" placeholder="shop@upi"></div><div class="field"><label>WhatsApp number</label><input id="posterWa" placeholder="919876543210"></div><div class="field"><label>Google Maps link</label><input id="posterMap" placeholder="https://maps.app.goo.gl/..."></div><div class="field"><label>Contact phone</label><input id="posterPhone" placeholder="+91 98765 43210"></div><div class="modal-actions"><button class="btn primary" id="printPoster">Print / Save PDF</button></div></div><div class="poster-preview"><div class="a4"><div class="eyebrow" style="justify-content:center">WELCOME</div><h2 id="posterTitle">Your Shop Name</h2><p>Scan a code to pay, order, find us or get in touch</p><div class="poster-grid" id="posterGrid"></div></div></div></div></div></div>`;

const $=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/([\\;,:"])/g,'\\$1').replace(/\n/g,'\\n');
function renderTabs(){ $('#tabs').innerHTML=Object.entries(types).map(([k,v])=>`<button class="tab ${k===state.type?'active':''}" data-type="${k}">${v.icon} ${v.label}</button>`).join(''); document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{state.type=b.dataset.type;renderTabs();renderFields();}); }
function renderFields(){const t=types[state.type];$('#formTitle').textContent=t.label+' QR';$('#fields').innerHTML=t.fields.map(([id,label,kind,val])=>{if(kind==='textarea')return `<div class="field full"><label for="${id}">${label}</label><textarea id="${id}" placeholder="${val}">${val}</textarea></div>`;if(kind==='select')return `<div class="field"><label for="${id}">${label}</label><select id="${id}">${val.split('|').map(x=>`<option>${x}</option>`).join('')}</select></div>`;return `<div class="field"><label for="${id}">${label}</label><input id="${id}" type="${kind}" placeholder="${val}" value="${val}"></div>`}).join('');$('#fields').querySelectorAll('input,textarea,select').forEach(x=>x.addEventListener('input',draw));draw();}
function payload(){const v=id=>$('#'+id)?.value.trim()||'';switch(state.type){case'whatsapp':return `https://wa.me/${v('phone').replace(/\D/g,'')}?text=${encodeURIComponent(v('message'))}`;case'upi':return `upi://pay?pa=${encodeURIComponent(v('upi'))}&pn=${encodeURIComponent(v('payee'))}${v('amount')?`&am=${encodeURIComponent(v('amount'))}`:''}${v('note')?`&tn=${encodeURIComponent(v('note'))}`:''}&cu=INR`;case'wifi':return `WIFI:T:${v('security')==='None'?'nopass':v('security')};S:${esc(v('ssid'))};P:${esc(v('password'))};H:${v('hidden')==='Yes'};;`;case'vcard':return `BEGIN:VCARD\nVERSION:3.0\nFN:${esc(v('name'))}\nORG:${esc(v('company'))}\nTEL:${esc(v('phone'))}\nEMAIL:${esc(v('email'))}\nADR:;;${esc(v('address'))};;;;\nURL:${esc(v('website'))}\nEND:VCARD`;case'email':return `mailto:${v('email')}?subject=${encodeURIComponent(v('subject'))}&body=${encodeURIComponent(v('body'))}`;case'phone':return `tel:${v('phone').replace(/\s/g,'')}`;default:return v('content')||'https://example.com';}}
function matrix(data,ecc=state.ecc){const qr=qrcode(0,ecc);qr.addData(data);qr.make();return qr;}
function paint(canvas,data,size=state.size,logo=state.logo){let qr;try{qr=matrix(data)}catch{qr=matrix(data,'L')}const n=qr.getModuleCount(),quiet=4,total=n+quiet*2,px=size/total;canvas.width=size;canvas.height=size;const c=canvas.getContext('2d');c.fillStyle=state.light;c.fillRect(0,0,size,size);c.fillStyle=state.dark;for(let r=0;r<n;r++)for(let col=0;col<n;col++)if(qr.isDark(r,col))c.fillRect(Math.floor((col+quiet)*px),Math.floor((r+quiet)*px),Math.ceil(px),Math.ceil(px));if(logo){const w=size*.2,x=(size-w)/2;c.fillStyle=state.light;c.beginPath();c.roundRect(x-size*.015,x-size*.015,w+size*.03,w+size*.03,size*.025);c.fill();c.drawImage(logo,x,x,w,w)}return qr;}
function draw(){paint($('#qrCanvas'),payload());}
function svgText(data){const qr=matrix(data),n=qr.getModuleCount(),q=4,total=n+q*2;let path='';for(let r=0;r<n;r++)for(let c=0;c<n;c++)if(qr.isDark(r,c))path+=`M${c+q} ${r+q}h1v1h-1z`;return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${total} ${total}" shape-rendering="crispEdges"><rect width="100%" height="100%" fill="${state.light}"/><path d="${path}" fill="${state.dark}"/></svg>`}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
$('#dark').oninput=e=>{state.dark=e.target.value;draw()};$('#light').oninput=e=>{state.light=e.target.value;draw()};$('#size').onchange=e=>{state.size=+e.target.value;draw()};$('#ecc').onchange=e=>{state.ecc=e.target.value;draw()};$('#logo').onchange=e=>{const f=e.target.files[0];if(!f)return;const im=new Image;im.onload=()=>{state.logo=im;draw()};im.src=URL.createObjectURL(f)};
$('#png').onclick=()=>{$('#qrCanvas').toBlob(b=>download(b,`qr-${state.type}.png`),'image/png')};$('#svg').onclick=()=>download(new Blob([svgText(payload())],{type:'image/svg+xml'}),`qr-${state.type}.svg`);
function posterData(){return [{name:'Pay with UPI',sub:$('#posterUpi').value||'Add your UPI ID',data:`upi://pay?pa=${encodeURIComponent($('#posterUpi').value)}&pn=${encodeURIComponent($('#shopName').value)}&cu=INR`},{name:'Order on WhatsApp',sub:$('#posterWa').value||'Add WhatsApp number',data:`https://wa.me/${$('#posterWa').value.replace(/\D/g,'')}?text=${encodeURIComponent('Hello, I would like to place an order.')}`},{name:'Find us on Maps',sub:'Open directions',data:$('#posterMap').value||'https://maps.google.com'},{name:'Save our contact',sub:$('#posterPhone').value||'Add contact number',data:`tel:${$('#posterPhone').value.replace(/\s/g,'')}`}];}
function renderPoster(){$('#posterTitle').textContent=$('#shopName').value||'Your Shop Name';$('#posterGrid').innerHTML=posterData().map((x,i)=>`<div class="poster-code"><canvas id="pc${i}"></canvas><b>${x.name}</b><span>${x.sub}</span></div>`).join('');posterData().forEach((x,i)=>paint($('#pc'+i),x.data,400,null));}
$('#shopKit').onclick=()=>{$('#posterModal').classList.add('open');renderPoster()};$('#closeModal').onclick=()=>$('#posterModal').classList.remove('open');$('#posterModal').onclick=e=>{if(e.target.id==='posterModal')e.currentTarget.classList.remove('open')};document.querySelectorAll('.poster-fields input').forEach(x=>x.oninput=renderPoster);$('#printPoster').onclick=()=>window.print();
renderTabs();renderFields();
